// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bank-recommendations': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bank-recommendations').default>>>>
    }
    '/api/company-news': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/company-news').default>>>>
    }
    '/api/company-profile': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/company-profile').default>>>>
    }
    '/api/company-search': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/company-search').default>>>>
    }
    '/api/financial-metrics': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/financial-metrics').default>>>>
    }
    '/api/finnhub-news': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finnhub-news').default>>>>
    }
    '/api/stock-news': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stock-news').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}